# Generated by Django 5.2.1 on 2025-05-26 07:43

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesgrandsvoisins_home', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Footers',
            },
        ),
    ]
