# Generated by Django 5.2.1 on 2025-05-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesgrandsvoisins_home', '0003_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='order',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
