# Generated by Django 5.2.1 on 2025-05-26 08:05

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesgrandsvoisins_home', '0004_footer_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='content',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='order',
        ),
        migrations.AddField(
            model_name='footer',
            name='contents',
            field=wagtail.fields.StreamField([('content', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
    ]
