initial:
	python -m venv .venv
	./.venv/bin/pip install --upgrade pip
	./.venv/bin/pip install -r requirements.txt
	./.venv/bin/django-admin startproject annuaire
	echo "SECRET_KEY="`./.venv/bin/python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'` >> .env