# Generated by Django 5.2.1 on 2025-05-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesgrandsvoisins_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='source_name',
        ),
        migrations.AddField(
            model_name='application',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
