# Generated by Django 5.2.1 on 2025-05-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesgrandsvoisins_admin', '0002_remove_application_source_name_application_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='icon',
            field=models.CharField(help_text="CSS class or icon name <a href='https://feathericons.com/'>feathericons.com</a>", max_length=100),
        ),
    ]
